// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRfgOdbIpFmaDaEYMeqJ7hVd2rUx2buzY',
    appId: '1:1087560828714:web:44c60b28cd0e21d4ee4053',
    messagingSenderId: '1087560828714',
    projectId: 'liveasy-internship-bd21a',
    authDomain: 'liveasy-internship-bd21a.firebaseapp.com',
    storageBucket: 'liveasy-internship-bd21a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQyTKb24UXaJeZ_JwIvKdDYZafTPUJVY',
    appId: '1:1087560828714:android:f6d78cafb0fd9341ee4053',
    messagingSenderId: '1087560828714',
    projectId: 'liveasy-internship-bd21a',
    storageBucket: 'liveasy-internship-bd21a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjDCmXnND3tCIDD_MdZQOah38dlGaXpAg',
    appId: '1:1087560828714:ios:35e38cfa1d8b6eabee4053',
    messagingSenderId: '1087560828714',
    projectId: 'liveasy-internship-bd21a',
    storageBucket: 'liveasy-internship-bd21a.appspot.com',
    iosBundleId: 'com.example.liveasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjDCmXnND3tCIDD_MdZQOah38dlGaXpAg',
    appId: '1:1087560828714:ios:35e38cfa1d8b6eabee4053',
    messagingSenderId: '1087560828714',
    projectId: 'liveasy-internship-bd21a',
    storageBucket: 'liveasy-internship-bd21a.appspot.com',
    iosBundleId: 'com.example.liveasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRfgOdbIpFmaDaEYMeqJ7hVd2rUx2buzY',
    appId: '1:1087560828714:web:2b8c6567a6a4a3d7ee4053',
    messagingSenderId: '1087560828714',
    projectId: 'liveasy-internship-bd21a',
    authDomain: 'liveasy-internship-bd21a.firebaseapp.com',
    storageBucket: 'liveasy-internship-bd21a.appspot.com',
  );
}
